---
# tasks file for roles/ubuntu-es
- name: install vsftpd ubuntu
  apt:
    name: vsftpd
    state: latest
    update_cache: yes

- name: disable firewall
  service:
    name: ufw
    state: stopped
    enabled: no

- name: create ftp user
  user:
    name: vaughncruz
    password: $gOzz0glRE29yIZZn6w5vZxrjZRlZSXFYz2ln8w2Am2WVPL6L614Tok0 
    comment: "FTP user successfully created"

- name: add deny user
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "DenyUser choong"
  register: ssh_config

- name: create ftp dir
  file:
    path: /home/vaughncruz/ftp
    state: directory
    owner: vaughncruz
    group: vaughncruz
    mode: '0555'

- name: create ftp files
  file:
    path: /home/vaughncruz/ftp/files
    state: directory
    owner: vaughncruz
    group: vaughncruz

- name: copy vsftpd.config
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
  register: vsftpd_config

- name: restart vsftpd.config
  service:
    name: vsftpd
    state: restarted
  when: vsftpd_config.changed
